# Generated by Django 4.1 on 2022-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('amount', models.CharField(max_length=122)),
                ('orderId', models.CharField(blank=True, max_length=122)),
                ('RazorPay_Payment_Id', models.CharField(blank=True, max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
